#version: '3.4'

#services:
#  webapi:
#    image: ${DOCKER_REGISTRY-}webapi
#    build:
#      context: .
#      dockerfile: web Api\Dockerfile


version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: web Api\Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Default: "Server=DESKTOP-VMQOHGF;Database=MiniTwitter;User Id=postgres;Trust Server Certificate=False;SSL Mode=Disable;Pooling=true;"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MiniTwitter
      POSTGRES_USER: postgres
    ports:
    - "5432:5432"